import type { ChronotopeTheme, ChronotopeThemeId } from '@/types/content';

/**
 * Identidade visual cronotópica: a linguagem visual evolui com o tempo
 * histórico (argila → papiro → pergaminho → impressão → caderno →
 * livro acadêmico → quadro-negro → tela digital). As transições entre
 * temas são sempre interpoladas (ver ThemeProvider), nunca abruptas.
 */
export const CHRONOTOPES: Record<ChronotopeThemeId, ChronotopeTheme> = {
  prehistoric: {
    id: 'prehistoric',
    label: 'Primeiros registros',
    bg: '#161310',
    bgAlt: '#1d1914',
    surface: '#23201a',
    ink: '#ece2d0',
    inkDim: '#a89c86',
    accent: '#c98a4b',
    accentAlt: '#8a6a4a',
    border: '#3a3226',
    texture: 'texture-clay',
    fontDisplay: "'Fraunces', serif",
  },
  mesopotamia: {
    id: 'mesopotamia',
    label: 'Mesopotâmia',
    bg: '#171310',
    bgAlt: '#1e1712',
    surface: '#28201a',
    ink: '#efe3cd',
    inkDim: '#b3a289',
    accent: '#c0793d',
    accentAlt: '#7d5a3a',
    border: '#40311f',
    texture: 'texture-clay',
    fontDisplay: "'Fraunces', serif",
  },
  egypt: {
    id: 'egypt',
    label: 'Egito',
    bg: '#151511',
    bgAlt: '#1b1b15',
    surface: '#242419',
    ink: '#f1e9cf',
    inkDim: '#b7ae8f',
    accent: '#d4af37',
    accentAlt: '#5f7a6b',
    border: '#3c3a26',
    texture: 'texture-papyrus',
    fontDisplay: "'Fraunces', serif",
  },
  classical: {
    id: 'classical',
    label: 'Mundo clássico',
    bg: '#131417',
    bgAlt: '#191b1f',
    surface: '#21242a',
    ink: '#ece9e2',
    inkDim: '#a9aab0',
    accent: '#c7b299',
    accentAlt: '#5b7a8c',
    border: '#33363d',
    texture: 'texture-marble',
    fontDisplay: "'Fraunces', serif",
  },
  'india-china': {
    id: 'india-china',
    label: 'Índia e China',
    bg: '#12151a',
    bgAlt: '#171b21',
    surface: '#1f242b',
    ink: '#eef0ea',
    inkDim: '#a6ad9f',
    accent: '#c1543c',
    accentAlt: '#3f8f7a',
    border: '#2c333b',
    texture: 'texture-paper',
    fontDisplay: "'Fraunces', serif",
  },
  islamic: {
    id: 'islamic',
    label: 'Mundo islâmico',
    bg: '#0f1518',
    bgAlt: '#141c20',
    surface: '#1a252a',
    ink: '#eaf1ee',
    inkDim: '#9fb3ac',
    accent: '#2f9e8f',
    accentAlt: '#c79a4b',
    border: '#233036',
    texture: 'texture-geometric',
    fontDisplay: "'Fraunces', serif",
  },
  medieval: {
    id: 'medieval',
    label: 'Europa medieval',
    bg: '#13110f',
    bgAlt: '#191614',
    surface: '#221e19',
    ink: '#ece3d3',
    inkDim: '#ab9f8a',
    accent: '#8c2f2f',
    accentAlt: '#39506b',
    border: '#362e24',
    texture: 'texture-parchment',
    fontDisplay: "'Fraunces', serif",
  },
  renaissance: {
    id: 'renaissance',
    label: 'Renascimento',
    bg: '#100f10',
    bgAlt: '#171518',
    surface: '#201d21',
    ink: '#f0e9df',
    inkDim: '#b0a89c',
    accent: '#b6862c',
    accentAlt: '#4a5f7a',
    border: '#332f34',
    texture: 'texture-parchment',
    fontDisplay: "'Fraunces', serif",
  },
  'scientific-revolution': {
    id: 'scientific-revolution',
    label: 'Revolução Científica',
    bg: '#0d0f12',
    bgAlt: '#131619',
    surface: '#1a1f24',
    ink: '#eceff2',
    inkDim: '#9aa4ad',
    accent: '#3f7cac',
    accentAlt: '#b6862c',
    border: '#262c32',
    texture: 'texture-paper',
    fontDisplay: "'Fraunces', serif",
  },
  enlightenment: {
    id: 'enlightenment',
    label: 'Século XVIII',
    bg: '#0d0e11',
    bgAlt: '#121419',
    surface: '#181b21',
    ink: '#edeff3',
    inkDim: '#9ba0ab',
    accent: '#4f7cac',
    accentAlt: '#8c6f3f',
    border: '#252932',
    texture: 'texture-paper',
    fontDisplay: "'Fraunces', serif",
  },
  nineteenth: {
    id: 'nineteenth',
    label: 'Século XIX',
    bg: '#0b0d10',
    bgAlt: '#0f1216',
    surface: '#161a1f',
    ink: '#eef0f2',
    inkDim: '#98a0aa',
    accent: '#7c5cad',
    accentAlt: '#4f7cac',
    border: '#22262e',
    texture: 'texture-grid',
    fontDisplay: "'Fraunces', serif",
  },
  modern: {
    id: 'modern',
    label: 'Século XX',
    bg: '#0a0b0d',
    bgAlt: '#0e1012',
    surface: '#15171a',
    ink: '#eef1f2',
    inkDim: '#93999f',
    accent: '#4fb0ac',
    accentAlt: '#c65b4e',
    border: '#20242a',
    texture: 'texture-grid',
    fontDisplay: "'Space Grotesk', sans-serif",
  },
  contemporary: {
    id: 'contemporary',
    label: 'Contemporânea',
    bg: '#08090b',
    bgAlt: '#0c0e10',
    surface: '#121417',
    ink: '#eef2f3',
    inkDim: '#8f979e',
    accent: '#5ad1c4',
    accentAlt: '#e2725b',
    border: '#1c2024',
    texture: 'texture-data',
    fontDisplay: "'Space Grotesk', sans-serif",
  },
};

export const CHRONOTOPE_ORDER: ChronotopeThemeId[] = [
  'prehistoric',
  'mesopotamia',
  'egypt',
  'classical',
  'india-china',
  'islamic',
  'medieval',
  'renaissance',
  'scientific-revolution',
  'enlightenment',
  'nineteenth',
  'modern',
  'contemporary',
];
